---
name: alpine-s6

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login - docker hub
        uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login - quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./alpine-s6
          file: ./alpine-s6/Dockerfile-3.13
          pull: true
          no-cache: true
          push: true
          tags: |
            shinomineko/alpine-s6:3.13
            quay.io/shinomineko/alpine-s6:3.13
