---
name: build all
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup qemu
        uses: docker/setup-qemu-action@v3.0.0

      - name: setup buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: login to registry
        uses: docker/login-action@v3.2.0
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: make build
        shell: bash
        env:
          PUSH: 'true'
          JOBS: '4'
          DOCKER_BUILDKIT: '1'
