---
name: build all

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        images: [aria2, htpasswd, httpie, jenkins-agent, nmap, ssh-honeypot, toolbox, torproxy, transmission]

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login - docker hub
        uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login - quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./${{ matrix.images }}
          file: ./${{ matrix.images }}/Dockerfile
          push: true
          tags: |
            shinomineko/${{ matrix.images }}:latest
            quay.io/shinomineko/${{ matrix.images }}:latest

