---
name: build all
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2.0.0
      - uses: docker/setup-buildx-action@v1.7.0
      - uses: docker/login-action@v1.14.1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: make build
        shell: bash
        env:
          PUSH: 'true'
          JOBS: '4'
          DOCKER_BUILDKIT: '1'
