---
name: build all

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login - docker hub
        uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login - quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: build and push - aria2
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./aria2
          file: ./aria2/Dockerfile
          push: true
          tags: |
            shinomineko/aria2:latest
            quay.io/shinomineko/aria2:latest

      - name: build and push - jenkins-agent
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./jenkins-agent
          file: ./jenkins-agent/Dockerfile
          push: true
          tags: |
            shinomineko/jenkins-agent:alpine
            quay.io/shinomineko/jenkins-agent:alpine

      - name: build and push - nmap
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./nmap
          file: ./nmap/Dockerfile
          push: true
          tags: |
            shinomineko/nmap:latest
            quay.io/shinomineko/nmap:latest

      - name: build and push - ssh-honeypot
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./ssh-honeypot
          file: ./ssh-honeypot/Dockerfile
          push: true
          tags: |
            shinomineko/ssh-honeypot:latest
            quay.io/shinomineko/ssh-honeypot:latest

      - name: build and push - toolbox
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./toolbox
          file: ./toolbox/Dockerfile
          push: true
          tags: |
            shinomineko/toolbox:latest
            quay.io/shinomineko/toolbox:latest

      - name: build and push - torproxy
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./torproxy
          file: ./torproxy/Dockerfile
          push: true
          tags: |
            shinomineko/torproxy:latest
            quay.io/shinomineko/torproxy:latest

      - name: build and push - transmission
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./transmission
          file: ./transmission/Dockerfile
          push: true
          tags: |
            shinomineko/transmission:latest
            quay.io/shinomineko/transmission:latest
