---
name: build all
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup qemu
        uses: docker/setup-qemu-action@v3.6.0

      - name: setup buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: login to registry
        uses: docker/login-action@v3.5.0
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: bake
        uses: docker/bake-action@v6.9.0
        with:
          push: true
          set: |
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
