---
name: jenkins-agent

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * 6'

  push:
    branches:
      - main
    paths:
      - jenkins-agent/**

  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login - docker hub
        uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login - quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: build and push - alpine
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./jenkins-agent
          file: ./jenkins-agent/Dockerfile-alpine
          pull: true
          no-cache: true
          push: true
          tags: |
            shinomineko/jenkins-agent:alpine
            quay.io/shinomineko/jenkins-agent:alpine

      - name: build and push - buster
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./jenkins-agent
          file: ./jenkins-agent/Dockerfile-buster
          pull: true
          no-cache: true
          push: true
          tags: |
            shinomineko/jenkins-agent:buster
            quay.io/shinomineko/jenkins-agent:buster

      - name: build and push - ubi8
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./jenkins-agent
          file: ./jenkins-agent/Dockerfile-ubi8
          pull: true
          no-cache: true
          push: true
          tags: |
            shinomineko/jenkins-agent:ubi8
            quay.io/shinomineko/jenkins-agent:ubi8
