---
name: ssh-honeypot

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ssh-honeypot/**

  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login
        uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./ssh-honeypot
          file: ./ssh-honeypot/Dockerfile
          pull: true
          no-cache: true
          tags: shinomineko/ssh-honeypot:latest
          push: true
