name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - uses: docker/setup-qemu-action@v1.2.0

      - uses: docker/setup-buildx-action@v1.6.0

      - uses: docker/build-push-action@v2.7.0
        with:
          context: ./toolbox
          push: false
          tags: |
            shinomineko/toolbox:latest
            quay.io/shinomineko/toolbox:latest
