---
name: toolbox

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * 6'

  push:
    branches:
      - main

  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: loging to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GLOBAL_GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./toolbox
          file: ./toolbox/Dockerfile
          pull: true
          no-cache: true
          push: true
          tags: |
            shinomineko/toolbox:latest
            ghcr.io/${{ github.repository_owner }}/toolbox:latest
