---
name: toolbox

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * 6'

  push:
    branches:
      - main
    paths:
      - toolbox/**

  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup qemu
        uses: docker/setup-qemu-action@v1

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login
        uses: docker/login-action@v1
        with:
          username: shinomineko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./toolbox
          file: ./toolbox/Dockerfile
          pull: true
          no-cache: true
          tags: shinomineko/toolbox:latest
          push: true
