---
name: trivy
on:
  workflow_run:
    workflows: ["build all"]
    types:
      - completed
jobs:
  trivy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [
          "aria2:latest",
          "htpasswd:latest",
          "httpie:latest",
          "jenkins-agent:latest-alpine-jdk8",
          "jenkins-agent:latest-alpine-jdk11",
          "jenkins-job-builder:latest",
          "mdbook:latest",
          "nginx-unprivileged:mainline",
          "nginx-unprivileged:mainline-alpine",
          "nmap:latest",
          "shellcheck:latest",
          "skopeo:latest",
          "squid:latest",
          "ssh-honeypot:latest",
          "toolbox:latest",
          "torproxy:latest",
          "transmission:latest"
        ]
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/shinomineko/${{ matrix.image }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-${{ matrix.image }}.sarif'
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-${{ matrix.image }}.sarif'
