---
name: trivy
on:
  workflow_run:
    workflows: ["build all"]
    types:
      - completed
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          IFS=$'\n'
          mapfile -t files < <(find -L . -iname '*Dockerfile' | sed 's|./||' | sed 's|/Dockerfile||' | sed 's|/|:|' | sort)
          unset IFS

          json="{\"image\":["
          for f in ${files[@]}; do
            j="\"$f\","
            if [[ "$json" != *"$j"* ]]; then
              json=$json$j
            fi
          done

          # remove last "," and add closing bracket
          if [[ "$json" == * ]]; then
            json="${json%?}"
          fi

          json="$json]}"
          echo $json

          # set output
          echo "::set-output name=matrix::$( echo "$json" )"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  trivy:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/shinomineko/${{ matrix.image }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-${{ matrix.image }}.sarif'
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-${{ matrix.image }}.sarif'
